version: "3"
services:
    travel-planner-project:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "4200:4200"
        container_name: travel-planner-project
        # volumes:
        #    - ./travel-planner-project:/app