/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f4fd2b33-02a1-4749-8c1d-02c304b158cd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r26l8b00Y",
    "aws_user_pools_web_client_id": "q24v72k1nscsoarhp395jb3m5",
    "oauth": {}
};


export default awsmobile;
