on:
  push:
    branches: [ master ]

name: Post Deployment Integration Test

jobs:
  deploy:
    name: Run UI IT test post Deployment
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: GoF-NUS-ISS/f-qa-integration-tests
        path: f-qa-integration-tests

    - name: Wait for URL to be responsive
      uses: nev7n/wait_for_response@v1
      with:
        url: "http://alb-travel-app-451787435.us-east-1.elb.amazonaws.com:4200"
        responseCode: 200
        timeout: 120000
        interval: 10000

    - name: Run Maven Command to Trigger UI Test Pack
      env:
        user_name: ${{ secrets.QA_UI_TEST_LOGIN_USER_NAME }}
        password: ${{ secrets.QA_UI_TEST_LOGIN_PASSWORD }}
      run: mvn -f f-qa-integration-tests/cucumber-selenium-fw/pom.xml clean install -Dbrowser=headless -Dusername=$user_name -Dpassword=$password -Dbase_url=http://alb-travel-app-451787435.us-east-1.elb.amazonaws.com:4200
 
    - name: Upload Test Artifcat
      uses: actions/upload-artifact@v2
      with:
        name: ui-test-report
        path: f-qa-integration-tests/cucumber-selenium-fw/target/html/htmlreport.html

      